[build-system]
requires = ["setuptools>=64", "wheel", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "orcabridge"
description = "Prototype Oracapod Pipeline implementation in Python"
dynamic = ["version"]
readme = "README.md"
requires-python = ">=3.6"
license = { text = "MIT License" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    # TODO: move this dependency to video_curator
    # List dependencies here, for example:
    # "numpy>=1.20.0",
    # "pandas>=1.3.0",

]

[project.urls]
Homepage = "https://github.com/walkerlab/orcabridge"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools_scm]
version_file = "src/orcabridge/_version.py"
